server:
  port: ${SERVER_PORT:9004}

spring:
  liquibase:
    change-log: classpath:db/init-db.xml
  graphql:
    path: /graphql
    websocket:
      path: /graphql
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"

logging:
  level:
    root: info
