server:
  port: ${SERVER_PORT:9004}

spring:
  liquibase:
    change-log: classpath:db/init-db.xml
  main:
    allow-bean-definition-overriding: true

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors:
      allowed-origins:
        - "*"
    tracing-enabled: true
  graphiql:
    mapping: /graphiql
    endpoint:
      graphql: /graphql
    basePath: /
    enabled: true
    cdn:
      enabled: false
      version: 0.17.5

logging:
  level:
    root: info

